name: clearml-ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      # ClearML credentials (store these in GitHub Actions Secrets)
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      CLEARML_WEB_HOST: ${{ secrets.CLEARML_WEB_HOST }}
      CLEARML_FILES_HOST: ${{ secrets.CLEARML_FILES_HOST }}

      # Project settings
      CLEARML_PROJECT: "ClearML_GHA_Demo"
      CLEARML_PIPELINE_NAME: "BreastCancer_Pipeline"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

    #   - name: Configure ClearML (write clearml.conf)
    #     run: |
    #         mkdir -p ~/.clearml
    #         cat > ~/clearml.conf << 'EOF'
    #         api {
    #             api_server: ${CLEARML_API_HOST}
    #             web_server: ${CLEARML_WEB_HOST}
    #             files_server: ${CLEARML_FILES_HOST}
    #         credentials {
    #             access_key: ${CLEARML_API_ACCESS_KEY}
    #             secret_key: ${CLEARML_API_SECRET_KEY}
    #                 }
    #             }
    #         sdk {
    #             development {
    #                 default_output_uri: ${CLEARML_FILES_HOST}
    #                         }
    #             }
    #         EOF

    #         echo "Wrote ~/clearml.conf"

    #   - name: Sanity check ClearML SDK connectivity
    #     run: |
    #         python -c "from clearml import Task; t=Task.init(project_name='${CLEARML_PROJECT}', task_name='gha_sanity'); print('Task ID:', t.id); t.close()"


      - name: Connectivity check to ClearML
        run: |
            echo "API:   $CLEARML_API_HOST"
            echo "WEB:   $CLEARML_WEB_HOST"
            echo "FILES: $CLEARML_FILES_HOST"
            curl -I --max-time 10 "$CLEARML_API_HOST" || true
            curl -I --max-time 10 "$CLEARML_WEB_HOST" || true
            curl -I --max-time 10 "$CLEARML_FILES_HOST" || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ClearML pipeline
        run: |
          python -m src.pipeline --project "${CLEARML_PROJECT}" --name "${CLEARML_PIPELINE_NAME}"